package main

// @title Flowix Metadata API
// @version 1.0
// @description Video metadata CRUD + internal status (Go chi). JWT Bearer required for write ops.
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer {token}" for JWT
import (
	"context"
	"log"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"

	_ "flowix/metadata/docs" // generated by swag init
	"flowix/metadata/internal/handler"
	mw "flowix/metadata/internal/middleware"
	"flowix/metadata/internal/repository"
	"flowix/metadata/internal/storage"
	pkghttp "flowix/pkg/httpserver"
	"flowix/pkg/httputil"
	pkglogger "flowix/pkg/logger"
	"flowix/pkg/metrics"
	pkgmw "flowix/pkg/middleware"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	port := os.Getenv("METADATA_PORT")
	if port == "" {
		port = "8002"
	}
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		dbURL = "postgres://flowix:flowix@localhost:5432/flowix?sslmode=disable"
	}
	// pgx doesn't like sslmode, strip it for compat (same as auth)
	dbURL = stripSSLMode(dbURL)
	// Phase 15: if PGBOUNCER_ENABLED, rewrite host to pgbouncer service (transaction pooling)
	if strings.ToLower(os.Getenv("PGBOUNCER_ENABLED")) == "true" && !strings.Contains(dbURL, "pgbouncer") {
		dbURL = strings.ReplaceAll(dbURL, "@postgres:", "@pgbouncer:")
		dbURL = strings.ReplaceAll(dbURL, "@postgres/", "@pgbouncer/")
		dbURL = strings.ReplaceAll(dbURL, "@localhost:", "@pgbouncer:")
		dbURL = strings.ReplaceAll(dbURL, "localhost:", "pgbouncer:")
		dbURL = strings.ReplaceAll(dbURL, "127.0.0.1:", "pgbouncer:")
	}
	jwtSecret := requireEnv("JWT_SECRET")
	internalToken := requireEnv("INTERNAL_TOKEN")
	minioEndpoint := os.Getenv("MINIO_ENDPOINT")
	if minioEndpoint == "" {
		minioEndpoint = "minio:9000"
	}
	bucket := os.Getenv("VIDEO_STORAGE_BUCKET")
	if bucket == "" {
		bucket = "videos"
	}
	minioAccess := os.Getenv("MINIO_ACCESS_KEY")
	minioSecret := os.Getenv("MINIO_SECRET_KEY")
	secure, _ := strconv.ParseBool(os.Getenv("MINIO_SECURE"))
	// zerolog console in dev, json in prod — общий bootstrap (issue #63)
	logger := pkglogger.Setup("metadata")

	// Phase 15: tune pool for PgBouncer (transaction mode requires simple protocol, no prepared statements)
	poolCfg, err := pgxpool.ParseConfig(dbURL)
	if err != nil {
		log.Fatalf("pgxpool parse: %v", err)
	}
	if v := os.Getenv("DATABASE_POOL_SIZE"); v != "" {
		if n, parseErr := strconv.Atoi(v); parseErr == nil && n > 0 {
			poolCfg.MaxConns = int32(n)
		}
	} else {
		// default 5 conns when behind PgBouncer, else pgx default
		if strings.Contains(dbURL, "pgbouncer") {
			poolCfg.MaxConns = 5
		}
	}
	if strings.Contains(dbURL, "pgbouncer") || strings.ToLower(os.Getenv("PGBOUNCER_ENABLED")) == "true" {
		poolCfg.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	}
	pool, err := pgxpool.NewWithConfig(context.Background(), poolCfg)
	if err != nil {
		log.Fatalf("pgxpool: %v", err)
	}
	defer pool.Close()
	if err := pool.Ping(context.Background()); err != nil {
		log.Fatalf("db ping: %v", err)
	}
	logger.Info().Str("port", port).Msg("metadata starting")

	repo := repository.NewVideoRepo(pool)
	var vh *handler.VideoHandler
	if minioEndpoint != "" && minioAccess != "" {
		if store, err := storage.NewMinioClient(minioEndpoint, minioAccess, minioSecret, bucket, secure); err == nil {
			// Issue #43: presigned thumbnail URLs for browsers must embed the public host
			publicEndpoint := os.Getenv("MINIO_PUBLIC_ENDPOINT")
			if publicEndpoint != "" {
				if presignErr := store.EnablePublicPresign(publicEndpoint, minioAccess, minioSecret, strings.HasPrefix(publicEndpoint, "https://")); presignErr == nil {
					logger.Info().Str("public_endpoint", publicEndpoint).Msg("metadata public presign enabled")
				} else {
					logger.Warn().Err(presignErr).Msg("public presign init failed, thumbnails will use internal endpoint")
				}
			}
			vh = handler.NewVideoHandlerWithStorage(repo, store)
			logger.Info().Str("bucket", bucket).Msg("metadata MinIO storage enabled for delete")
		} else {
			logger.Warn().Err(err).Msg("minio init failed, delete will not clean S3")
			vh = handler.NewVideoHandler(repo)
		}
	} else {
		vh = handler.NewVideoHandler(repo)
	}

	r := chi.NewRouter()
	r.Use(middleware.RequestID, middleware.Recoverer, pkgmw.RequestLogger("metadata"))

	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		httputil.WriteJSON(w, r, http.StatusOK, map[string]string{"status": "ok", "service": "metadata"})
	})
	r.Get("/metrics", metrics.Handler().ServeHTTP)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		httputil.WriteJSON(w, r, http.StatusOK, map[string]string{"service": "metadata", "version": "0.1"})
	})
	r.Get("/swagger/*", httpSwagger.WrapHandler)
	r.Get("/openapi.json", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/doc.json", http.StatusMovedPermanently)
	})
	// protected routes: need JWT
	r.Group(func(r chi.Router) {
		r.Use(pkgmw.AuthMiddleware(jwtSecret))
		r.Post("/api/v1/videos", vh.Create)
		r.Patch("/api/v1/videos/{id}", vh.Update)
		r.Delete("/api/v1/videos/{id}", vh.Delete)
	})
	// public list/get: optional JWT — владелец видит свои private/unlisted
	// (issue #44). Идентичность только из собственного JWT (X-User-ID не
	// доверенный — metadata опубликована наружу).
	optAuth := pkgmw.OptionalAuth(jwtSecret)
	r.With(optAuth).Get("/api/v1/videos", vh.List)
	r.With(optAuth).Get("/api/v1/videos/{id}", vh.Get)
	// internal — protected by X-Internal-Token (gateway/nginx/transcoder)
	r.Group(func(r chi.Router) {
		r.Use(mw.InternalAuth(internalToken))
		r.Patch("/internal/videos/{id}/status", vh.UpdateStatus)
		r.Get("/internal/videos/{id}", vh.GetInternal)
		r.Get("/internal/videos/{id}/vod", vh.GetVODMapping)
	})

	log.Printf("metadata listening :%s", port)
	// маленькие JSON-тела — литеральные таймауты issue #63 (Read 15s, Write 60s, Idle 120s)
	if err := pkghttp.Run(":"+port, r, pkghttp.Defaults()); err != nil {
		log.Fatal(err)
	}
}

func stripSSLMode(s string) string {
	if !strings.Contains(s, "sslmode=") {
		return s
	}
	u, err := url.Parse(s)
	if err != nil {
		return s
	}
	q := u.Query()
	q.Del("sslmode")
	u.RawQuery = q.Encode()
	return u.String()
}

// requireEnv reads a mandatory env var and exits with a clear error when it is
// empty — unless ENV=dev (local `make dev-*` runs without .env, issue #53).
// Empty INTERNAL_TOKEN previously left /internal/* metadata open.
func requireEnv(k string) string {
	v := os.Getenv(k)
	if v == "" && os.Getenv("ENV") != "dev" {
		log.Fatalf("required environment variable %s is empty — set it in .env (see .env.example)", k)
	}
	return v
}
